seed: 42
model_name: "xgboost"
model_params:
  alpha: 50.40580029434661
  gamma: 0.11
  gpu_id: 0
  lambda: 8.242035791320554
  learning_rate: 0.14
  max_depth: 2
  n_estimators: 980
  tree_method: gpu_hist

# model_name: "lgboost"
#model_name: "catboost"
#model_name: "lr"
#model_name: "e_net"
#model_name: "lasso"
#model_name: "ridge"
#model_name: "l_svr"
#model_name: "svr"
